appointments/urls.py
from django.urls import path
from . import views

app_name="appointments"

urlpatterns = [
    path('', views.AppointmentFormView.as_view(), name="appointment-form"),
    path('appointment-confirmation/<str:submission_token>/', views.AppointmentConfirmationView.as_view(), name='appointment-confirmation-page'),
    path('available-times/', views.available_times, name="available-times"),
]

common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

diary/urls.py
from django.urls import path
from . import views

app_name="diary"

urlpatterns = [
    path('', views.DiaryView.as_view(), name="diary"),
]

scheduling/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # JET urls
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    
    # Django Browser Reload
    path("__reload__/", include("django_browser_reload.urls")),
    
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('appointments/', include('appointments.urls')),
    path('diary/', include('diary.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointments/models.py
from django.db import models
from django.utils import timezone
from common.utils import generate_unique_token
from accounts.models import CustomUser

from datetime import datetime
import calendar

DAYS_WEEK = [(i, list(calendar.day_name)[i]) for i in range(len(list(calendar.day_name)))]

class Holiday(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateField()
    
    class Meta:
        ordering = ['-date']
        
    def __str__(self):
        return self.name


class WeekDay(models.Model):
    name = models.IntegerField(unique=True, choices=DAYS_WEEK)

    def __str__(self):
        return self.get_name_display()

    class Meta:
        verbose_name = 'Week Days Available for Appointments'
        verbose_name_plural = 'Week Days Available for Appointments'


class AppointmentTime(models.Model):
    time = models.TimeField(max_length=8)
    week_days = models.ManyToManyField(WeekDay)

    def __str__(self):
        return self.time.strftime('%H:%M')

    class Meta:
        verbose_name = 'Available Times for Appointments'
        verbose_name_plural = 'Available Times for Appointments'


class Appointment(models.Model):
    user = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=25)
    email = models.EmailField(max_length=255)
    appointment_date = models.DateField()
    appointment_time = models.ForeignKey(AppointmentTime, on_delete=models.PROTECT)
    appointment_created_date = models.DateTimeField(auto_now_add=True)
    note = models.TextField(null=True, blank=True)
    token = models.CharField(max_length=100, default=generate_unique_token, unique=True)
    token_expiry_date = models.DateField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk and not self.token_expiry_date:
            self.token_expiry_date = self.appointment_date
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.name} {self.surname}'s appointment on {self.appointment_date} at {self.appointment_time}"
    
    class meta:
        ordering = ('-appointment_date', '-appointment_time')
    
    @staticmethod
    def get_available_times(date):
        
        parsed_date = datetime.strptime(date, '%Y-%m-%d').date()
        
        is_holiday = Holiday.objects.filter(date=date).exists()
        is_today = timezone.now().date() == parsed_date
        now = timezone.now()
            
        if is_holiday:
            available_times = []
            return available_times
            
        day_of_week = parsed_date.weekday()

        if is_today:
            all_times = AppointmentTime.objects.filter(week_days__name=day_of_week, time__gt=now)
        else:
            all_times = AppointmentTime.objects.filter(week_days__name=day_of_week)
        
        existing_appointments = Appointment.objects.filter(appointment_date=date).values_list('appointment_time__time', flat=True)

        available_times = [{
            'time_label': appointment_time.time.strftime('%H:%M'),
            'time_value': appointment_time.id,
        } for appointment_time in all_times if appointment_time.time not in existing_appointments]

        return available_times

appointments/forms.py
from django.core.exceptions import ValidationError
from django import forms
from django.utils import timezone

from .models import Appointment, Holiday

class AppointmentForm(forms.ModelForm):
    
    class Meta:
        model = Appointment
        fields = '__all__'
        exclude = ['token', 'token_expiry_date']

    def clean(self):
        cleaned_data = super().clean()

        appointment_date = cleaned_data.get('appointment_date')

        if appointment_date < timezone.now().date():
            raise ValidationError({'appointment_date': ['This date is not a valid date.']})

        is_holiday = Holiday.objects.filter(date=appointment_date).exists()
            
        if is_holiday:
            raise ValidationError({'appointment_date': ['This date is not a valid date.']})

        appointment_time = cleaned_data.get('appointment_time')

        existing_appointment = Appointment.objects.filter(
            appointment_date=appointment_date,
            appointment_time=appointment_time
        ).exclude(pk=self.instance.pk if self.instance else None)

        if existing_appointment.exists():
            raise ValidationError({'appointment_time': ['This time is not available for your appointment.']})

        return cleaned_data

appointments/views.py
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.http import JsonResponse, Http404
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.template.loader import get_template
from django.conf import settings
from django.utils import timezone

from appointments.forms import AppointmentForm
from appointments.models import Appointment


class AppointmentFormView(FormView):
    template_name = 'appointments/appointment_form.html'
    form_class = AppointmentForm
    success_url = reverse_lazy('appointments:appointment-confirmation-page')

    def get_context_data(self, **kwargs):
        context = super(AppointmentFormView, self).get_context_data(**kwargs)
        context['today_date'] = timezone.now().strftime('%Y-%m-%d')
        return context
    
    def form_valid(self, form):

        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
            form.instance.name = self.request.user.first_name
            form.instance.surname = self.request.user.last_name
            form.instance.email = self.request.user.email
            if self.request.user.phone_number:
                form.instance.phone_number = self.request.user.phone_number
        
        if form.is_valid():
            submission = form.save()

            # Send mail?

            return redirect('appointments:appointment-confirmation-page', submission_token=submission.token)

        return super().form_valid(form)
 
    
class AppointmentConfirmationView(TemplateView):
    template_name = 'appointments/appointment_confirmation.html'

    def get(self, request, submission_token):

        try:
            submitted_data = Appointment.objects.get(token=submission_token)
        except Appointment.DoesNotExist:
            raise Http404

        context = {'submitted_data': submitted_data}
        return render(request, self.template_name, context)


def available_times(request):
    selected_day = request.GET.get('selectedDay')

    if not selected_day:
        return JsonResponse([], safe=False)
    
    available_times = Appointment.get_available_times(selected_day)
    
    return JsonResponse(available_times, safe=False)

appointments/templates/appointments/appointment-confirmation.html
{% extends 'base.html' %}

{% comment %} {% load custom_tags %}
{% load static %}  {% endcomment %}

{% block content %}

<div class="container">

    <h2 class="title text-center margin-top">{{ submitted_data.nombre|title }}, ¡tu cita ha sido <span class="text-primary-color">confirmada</span>!</h2>

    <p class="text-primary-color-dark text-center">En breves recibirás un correo a <span class="text-primary-color underlined">{{ submitted_data.email }}</span> con los detalles de la cita. Si no te llega ningún correo, 
    <a href="{% url 'web:contact_form' %}" class="animated-link">contáctanos</a> o envíanos un Whatsapp. Gracias por confiar en nosotros.</p>

    <p class="subtitle text-center margin-top">Te esperamos el día <span class="text-primary-color text-extra-bold">{{ submitted_data.fecha_cita }} a las {{ submitted_data.hora_cita }}</span>.</p>
    <p class="secondary-text text-center">No dudes en <a href="{% url 'web:contact_form' %}" class="animated-link">contactarnos</a> para cualquier tipo de consulta. Estamos a tu disposición.</p>

    <div class="margin-top center-element">
        <a href="{% url 'web:index' %}" class="button-primary">Volver al inicio</a>
    </div>

</div>

{% endblock %}

appointments/templates/appointments/appointment-form.html
{% extends 'base.html' %}

{% load custom_tags %}
{% load static %} 

{% block content %}

<div class="appointment-form-container">


    <div class="form-wrapper">

        <div class="form-hero-wrapper text-white">
            <div class="form-hero">
                <h2 class="text-center text-white title">Reserva tu cita</h2>
                <p class="text-center text-white secondary-text">
                    Completa el formulario para enviar tu solicitud
                </p>
            </div>
        </div>
    
        <form class="form" method="post">
            {% csrf_token %}

            <p class="secondary-text">Reserva tu cita rellenando este formulario. Sencillo y rápido. Recibirás un correo con la confirmación de la cita.</p>

            <div class="double-input-container">
                <div class="input-wrapper {% if form.nombre.errors %}has-error{% endif %}">
                    <input class="input" type="text" id="id-nombre" name="nombre" required placeholder=" " />
                    <label class="label" for="id-nombre">Nombre *</label>
                </div>
    
                <div class="input-wrapper {% if form.apellidos.errors %}has-error{% endif %}">
                    <input class="input" type="text" id="id-apellidos" name="apellidos" required placeholder=" " />
                    <label class="label" for="id-apellidos">Apellidos *</label>
                </div>
            </div>
    
            <div class="double-input-container">
                <div class="input-wrapper {% if form.numero_telefono.errors %}has-error{% endif %}">
                    <input class="input" type="text" id="id-numero_telefono" name="numero_telefono" required placeholder=" " />
                    <label class="label" for="id-numero_telefono">Número teléfono *</label>
                </div>
                <div class="input-wrapper {% if form.email.errors %}has-error{% endif %}">
                    <input class="input" type="email" id="id-email" name="email" required placeholder=" " />
                    <label class="label" for="id-email">Correo electrónico *</label>
                </div>
            </div>
    
            <div class="double-input-container">
                <div class="input-wrapper {% if form.fecha_cita.errors %}has-error{% endif %}">
                    <input class="input" type="date" id="id-fecha_cita" name="fecha_cita" required placeholder=" " />
                    <label class="label" for="text">Fecha de la cita *</label>
                </div>
    
                <div class="select-wrapper {% if form.hora_cita.errors %}has-error{% endif %} ">
                    <select class="select" id="id-hora_cita" name="hora_cita">
                        <option selected id="default-time-option" disabled="disabled">Seleccione un día para ver las horas disponibles</option>
                    </select>
                    <label class="label" for="text">Hora de la cita *</label>
                </div>
            </div>

            <div class="input-wrapper">
                <textarea class="input" id="id-comentarios" name="comentarios" placeholder=" "></textarea>
                <label class="label" for="id-comentarios">Comentarios</label>
            </div>
    
            <p class="secondary-text">Los campos con * son obligatorios.</p>            

            <div class="form-errors">
                {% for field, errors in form.errors.items %}            
                        <p class="error"><strong>{{ field|capfirst }}</strong>:&nbsp;{% for error in errors %}{{ error }}&nbsp;{% endfor %}</p>
                {% endfor %}

                {% for errors in form.non_field_errors.items %}            
                        <p class="error">{% for error in errors %}{{ error }}&nbsp;{% endfor %}</p>
                {% endfor %}
            </div>

            <button class="submit-button button-primary button-primary_small" type="submit">Reservar Cita</button>
            <p class="secondary-text">Al enviar el formulario indica que usted esta de acuerdo con los <a href="{% url 'web:terms_and_conditions' %}" class="animated-link">términos y condiciones</a>.</p>
        
        </form>

    </div>

    {% url 'appointments:available_time' as available_time_url %}
    <script>
        const csrftoken = Cookies.get('csrftoken');

        async function getAvailableTimes() {

            const appointmentDate = document.getElementById('id-fecha_cita').value;

            const selectedDay = { selected_day: appointmentDate };
            const payload = JSON.stringify(selectedDay);

            try {
                const response = await fetch("{{ available_time_url }}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": csrftoken,
                        'Content-Type': 'application/json',
                    },
                    body: payload,
                });
        
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
        
                const data = await response.json();
                return data;
            } catch (error) {
                console.error(error);

                return [];
            }
        }

        async function setAvailableTimes() {
            const selectInputAppointmentTime = document.getElementById("id-hora_cita");
            const defaultOption = document.getElementById("default-time-option");
            const availableTimes = await getAvailableTimes();
            
            try {
                selectInputAppointmentTime.innerHTML = '';
        
                selectInputAppointmentTime.appendChild(defaultOption)
                
                for (const time of availableTimes) {
                    const option = document.createElement("option");

                    option.value = time.time_value;
                    option.text = time.time_label;
                    selectInputAppointmentTime.appendChild(option);
                }
            } catch (error) {
                console.error("An error occurred:", error);
            }
        }

        document.getElementById("id-fecha_cita").addEventListener("change", setAvailableTimes);
    </script>

</div>

{% endblock %}

appointments/templates/appointments/appointment_confirmation.html
{% extends 'common/_main.html' %}

{% comment %} {% load custom_tags %}
{% load static %}  {% endcomment %}

{% block content %}

<main class="flex-1 flex flex-col justify-center items-center gap-4 text-sky-900">

    <h2 class="text-6xl max-md:text-4xl font-black text-center mx-3">{{ submitted_data.name|title }}, ¡your appointment has been <span class="text-yellow-500">confirmed</span>!</h2>

    <p class="text-sky-900/60 text-center">You will recieve a mail with appointment details.</p>

    <p class="text-xl font-bold text-center">We will be waiting for you on <span class="text-yellow-500 italic">{{ submitted_data.appointment_date }} at {{ submitted_data.appointment_time }}</span>.</p>

    <a href="{% url 'common:index' %}" class="italic group transition duration-300 hover:text-yellow-500">
        <span>Back to index</span>
        <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-yellow-500"></span>
    </a>

</main>

{% endblock %}

appointments/templates/appointments/appointment_form.html
{% extends 'common/_main.html' %}
{% load static %} 

{% block content %}

<main class="flex-1 bg-gray-50-700 text-sky-900 grid place-items">

    <div class="grid place-items-center py-8">
    
        <div class="bg-gray-50 w-11/12 max-w-[1400px] rounded-md shadow-md overflow-hidden flex max-lg:flex-col-reverse">
            <form class="w-1/2 max-lg:w-full p-12 flex flex-col gap-4 " method="post">
                {% csrf_token %}
                <p class="secondary-text">Book your appointment by filling up the form.</p>
    
                <div class="flex gap-4 items-center max-sm:flex-col">
                    <div class="group w-full">
                        <label for="name-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.name.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Name *</label>
                        <input {% if user.is_authenticated %} readonly="true" value="{{user.first_name}}" {% endif %} required type="text" id="name-input" name="name" required placeholder="Name" class="bg-gray-50 border-sky-900/20 border-2 h-12 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 read-only:opacity-50 {% if form.name.errors %}!placeholder-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}" />
                    </div>
        
                    <div class="group w-full">
                        <label for="surname-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.surname.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Surname *</label>
                        <input {% if user.is_authenticated %} readonly="true" value="{{user.last_name}}" {% endif %} required type="text" id="surname-input" name="surname" required placeholder="Surname" class="bg-gray-50 border-sky-900/20 border-2 h-12 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 read-only:opacity-50 {% if form.surname.errors %}!placeholder-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}" />
                    </div>
                </div>

                <div class="flex gap-4 items-center max-sm:flex-col">
                    <div class="group w-full">
                        <label for="phone_number-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.phone_number.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Phone Number *</label>
                        <input {% if user.is_authenticated and user.phone_number %} readonly="true" value="{{user.phone_number}}" {% endif %} required type="text" id="phone_number-input" name="phone_number" placeholder="Phone Number" class="bg-gray-50 border-sky-900/20 border-2 h-12 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 read-only:opacity-50 {% if form.phone_number.errors %}!placeholder-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}" />
                    </div>
        
                    <div class="group w-full">
                        <label for="email-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.email.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Email *</label>
                        <input {% if user.is_authenticated %} readonly="true" value="{{user.email}}" {% endif %} required type="email" id="email-input" name="email" required placeholder="Email" class="bg-gray-50 border-sky-900/20 border-2 h-12 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 read-only:opacity-50 {% if form.email.errors %}!placeholder-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}" />
                    </div>
                </div>

                <div class="flex gap-4 items-center max-sm:flex-col">
                    <div class="group w-full">
                        <label for="appointment_date-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.appointment_date.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Date *</label>
                        <input min="{{today_date}}" required type="date" id="appointment_date-input" name="appointment_date" required placeholder="Date" class="bg-gray-50 border-sky-900/20 border-2 h-12 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 {% if form.appointment_date.errors %}!text-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}" />
                    </div>
        
                    <div class="group w-full">
                        <label for="appointment_time-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.appointment_time.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Time *</label>
                        <select required type="text" id="appointment_time-input" name="appointment_time" required placeholder="Time" class="bg-gray-50 border-sky-900/20 border-2 h-12 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 {% if form.appointment_time.errors %}!text-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}" />
                            <option selected id="default-time-option" disabled="disabled">Pick a date first.</option>
                        </select>
                    </div>
                </div>
    
                <div class="group w-full">
                    <label for="note-input" class="block font-bold w-full pb-2 text-md transition-all duration-200 ease-in-out {% if form.note.errors %}text-red-600/80 group-focus-within:text-red-600/80{% else %} group-focus-within:text-yellow-500 {% endif %}">Note</label>
                    <textarea id="note-input" name="note" placeholder="Note" class="bg-gray-50 border-sky-900/20 border-2 h-32 w-full placeholder-sky-900/80 group-focus-within:border-yellow-500 rounded-md px-3 outline-none transition-all duration-200 ease-in-out bg-gray-50-700 focus:ring-0 {% if form.note.errors %}!placeholder-red-600/80 !border-red-600/80 !group-focus-within:border-red-500{% endif %}"></textarea>
                </div>
        
                <p class="italic text-sky-900/50">Fields flagged with * are required.</p>            
    
                <div class="flex flex-col gap-4">
                    {% for field, errors in form.errors.items %}            
                            <p class="text-red-600/80"><strong>{{ field|capfirst }}</strong>:&nbsp;{% for error in errors %}{{ error }}&nbsp;{% endfor %}</p>
                    {% endfor %}
    
                    {% for errors in form.non_field_errors.items %}            
                            <p class="text-red-600/80">{% for error in errors %}{{ error }}&nbsp;{% endfor %}</p>
                    {% endfor %}
                </div>
    
                <button class="h-12 rounded-md bg-sky-900 transition-colors hover:bg-sky-800 text-white" type="submit">Book Appointment</button>
                <p class="text-sky-900/50">By sending this form you accept our <span class="underline">terms & conditions</span>.</p>
            
            </form>
            <div class="w-1/2 max-lg:w-full relative max-lg:min-h-96">
                <div class="relative z-30 w-11/12 h-full mx-auto py-6 flex flex-col gap-2 items-center justify-center max-lg:min-h-96">
                    <h2 class="text-center text-5xl max-sm:text-3xl text-gray-50 font-black">Book your <span class="underline text-yellow-500 decoration-yellow-500">appointment</span>!</h2>
                    <p class="text-gray-50 text-center secondary-text">Fill the form to fulfill your appointment.</p>
                </div>
                <img class="z-10 h-full max-lg:min-h-96 w-full object-cover brightness-50 absolute top-0 left-0" src="{% static 'images/appointment_form_image.png' %}" alt="Appointment form image">
            </div>
        </div>

    </div>

    <script>
        function getCookie(cname) {
            let name = cname + "=";
            let decodedCookie = decodeURIComponent(document.cookie);
            let ca = decodedCookie.split(';');
            for(let i = 0; i <ca.length; i++) {
                let c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }

        const csrftoken = getCookie('csrftoken');

        async function getAvailableTimes() {

            const appointmentDate = document.getElementById('appointment_date-input').value;

            try {
                const response = await fetch(`{% url 'appointments:available-times' %}?selectedDay=${appointmentDate}`, {
                    method: "GET",
                    headers: {
                        "X-CSRFToken": csrftoken,
                        'Content-Type': 'application/json',
                    },
                });
        
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
        
                const data = await response.json();
                return data;
            } catch (error) {
                console.error(error);

                return [];
            }
        }

        async function setAvailableTimes() {
            const selectInputAppointmentTime = document.getElementById("appointment_time-input");
            const defaultOption = document.getElementById("default-time-option");
            const availableTimes = await getAvailableTimes();
            
            try {
                selectInputAppointmentTime.innerHTML = '';
        
                selectInputAppointmentTime.appendChild(defaultOption)
                
                for (const time of availableTimes) {
                    const option = document.createElement("option");

                    option.value = time.time_value;
                    option.text = time.time_label;
                    selectInputAppointmentTime.appendChild(option);
                }
            } catch (error) {
                console.error("An error occurred:", error);
            }
        }

        document.getElementById("appointment_date-input").addEventListener("change", setAvailableTimes);
    </script>

</main>

{% endblock %}