accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.UserRegistrationFormView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

appointments/urls.py
from django.urls import path
from . import views

app_name="appointments"

urlpatterns = [
    path('', views.AppointmentFormView.as_view(), name="appointment-form"),
    path('appointment-confirmation/<str:submission_token>/', views.AppointmentConfirmationView.as_view(), name='appointment-confirmation-page'),
    path('available-times/', views.available_times, name="available-times"),
]

common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

diary/urls.py
from django.urls import path
from . import views

app_name="diary"

urlpatterns = [
    path('', views.DiaryView.as_view(), name="diary"),
]

scheduling/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # JET urls
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    
    # Django Browser Reload
    path("__reload__/", include("django_browser_reload.urls")),
    
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('accounts/', include('accounts.urls')),
    path('appointments/', include('appointments.urls')),
    path('diary/', include('diary.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

class IndexView(TemplateView):
    template_name = 'common/index.html'

common/templates/common/base/footer.html
<footer class="p-12 text-center shadow-md text-white bg-sky-900">
    <p class="text-center font-light text-2xl italic">This is a footer &copy;</p>
</footer>

common/templates/common/base/head.html
{% load static tailwind_tags %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scheduling App</title>

    {% tailwind_css %}
</head>

common/templates/common/base/header.html
<header class="sticky z-50 top-0 p-8 text-center bg-sky-950 text-gray-50">
    <div class="w-11/12 max-w-[1200px] mx-auto flex justify-between items-center gap-6">
        <h1 class="text-2xl font-black italic tracking-tight">
            <a href="{% url 'common:index' %}">Django Scheduler</a>
        </h1>
        <div class="flex gap-4 items-center">
            <a href="{% url 'appointments:appointment-form' %}" class="group transition duration-300 hover:text-yellow-500">
                <span>Book an appointment</span>
                <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-yellow-500"></span>
            </a>
            {% if user.is_authenticated %}
            <a href="{% url 'diary:diary' %}" class="group transition duration-300 hover:text-yellow-500">
                <span>Diary</span>
                <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-yellow-500"></span>
            </a>
            {% endif %}
            <div>
                {% include 'common/base/session_manager.html' %} 
            </div>
        </div>
    </div>
</header>

common/templates/common/base/session_manager.html
{% if user.is_authenticated %}
<div class="group relative cursor-pointer">
    <div class="flex items-center justify-between space-x-5">
        <img class="rounded-full aspect-1 h-10" src="{{ user.profile_picture_url }}" alt="User's profile picture">
    </div>

    <div class="hidden absolute top-8 right-0 z-50 rounded-md w-max group-hover:flex flex-col min-w-36">
        <div class="h-4 bg-transparent w-full"></div>
        <div class="shadow-md bg-white rounded-md flex flex-col items-end overflow-hidden">
            <a href="{% url 'accounts:profile' %}" class="text-sky-900 font-bold px-3 py-2 w-full hover:bg-gray-50 transition-colors" href="">Profile</a>
            <form action="{% url 'accounts:logout' %}" method="POST" class="text-sky-900 font-bold px-3 py-2 w-full hover:bg-gray-50 transition-colors">
                {% csrf_token %}
                <button class="text-red-400" type="submit">Logout</button>
            </form>
        </div>
    </div>
</div>
{% else %}
    <a href="{% url 'accounts:login' %}" class="group transition duration-300 hover:text-yellow-500">
        <span>Login</span>
        <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-yellow-500"></span>
    </a>
{% endif %}